---
- hosts: 172.31.21.9 
  become: yes
  tasks:
  - name: install git
    apt:
     name: git
     state: present

  - name: isntall tree
    apt: 
      name: tree
      stateeee: present
    ignore_errors: yes

  - name: install wget
    apt: 
      name: wget
      state: present